# Generated by Django 3.1.6 on 2021-04-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WA_Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=1000)),
                ('program', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WA_Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('loc', models.CharField(blank=True, max_length=20, null=True)),
                ('org', models.CharField(blank=True, max_length=100, null=True)),
                ('postal', models.CharField(blank=True, max_length=15, null=True)),
                ('timezone', models.CharField(blank=True, max_length=30, null=True)),
                ('site_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitors_site', to='Tracking_app.wa_site')),
            ],
        ),
        migrations.CreateModel(
            name='WA_Timelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.DateTimeField()),
                ('time_diff', models.FloatField(blank=True, null=True)),
                ('page_name', models.CharField(blank=True, default='a', max_length=100)),
                ('site_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timelog_site', to='Tracking_app.wa_site')),
                ('visitors_ip', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitors_timelog', to='Tracking_app.wa_visitors')),
            ],
        ),
        migrations.CreateModel(
            name='WA_Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=30)),
                ('browser', models.CharField(max_length=20)),
                ('site_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resource_site', to='Tracking_app.wa_site')),
                ('visitors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors_resource', to='Tracking_app.wa_visitors')),
            ],
        ),
        migrations.CreateModel(
            name='WA_reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referene', models.CharField(max_length=50)),
                ('site_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference_site', to='Tracking_app.wa_site')),
                ('visitors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors_reference', to='Tracking_app.wa_visitors')),
            ],
        ),
        migrations.CreateModel(
            name='WA_OrderTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('site_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordertrack_site', to='Tracking_app.wa_site')),
                ('visitors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors_ordertrack', to='Tracking_app.wa_visitors')),
            ],
        ),
    ]
