# Generated by Django 3.1.6 on 2021-04-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking_app', '0002_wa_visitors_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wa_timelog',
            name='in_time',
            field=models.DateTimeField(),
        ),
    ]
