# Generated by Django 3.1.6 on 2021-04-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking_app', '0003_auto_20210410_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wa_reference',
            old_name='referene',
            new_name='reference',
        ),
    ]
